import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo & Google Note</title>
        <meta name="description" content="Generated by Muhammad Nasir" />
        <link rel="icon" href="/LN2.png" />
      </Head>
    </div>
  )
}
